# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d7fc4759ffa4a3fce6498db3d226c3a35bd7d19a560c7813bf1635018dd4be910efa593da9e0c30cd8d2194b17e7991c412d3ce012148c865ffaf62904d8417

test:
  secret_key_base: adbe34cc21fc17aa8411d3290e1c85e8311e56ea0c58ee29ef223b1f88574b51c690757ae5d96774f1abad8a09fc5a0be8d0a421de8c665baec8ff0b29d169f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
